version: '3'

services:
  postgrestri:
    image: postgres
    container_name: postegres-tricount-db
    environment:
      POSTGRES_USER: tricount
      POSTGRES_PASSWORD: tricount-pwd
      POSTGRES_DB: tricount
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  back:
    image: hugo08/hugo_repo:triback-20
    ports:
    - "3000:3000"
    environment:
      PG_USER: "tricount"
      PG_HOST: "postgrestri"
      PG_DATABASE: "tricount"
      PG_PASSWORD: "tricount-pwd"
      PG_PORT: "5432"
      ORIGIN: "http://localhost:3000"
      PRIVATE_KEY: "azeReed3R23RF32f"
      COOKIE_DOMAIN: "localhost:3000"
  front:
    image: hugo08/hugo_repo:trifront-3
    ports:
      - "8080:80"
    environment:
      VUE_APP_ADDRESS: "back"
  


volumes:
  pg_data: